# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


'''
上面的list array只會把第一層的元素轉換成 List，多層的話只有第一層會轉，且print出來的結果會出現array
而tolist() 才能達成多層的型態轉換
'''

### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [ ]:
# 記得先 Import 正確的套件

'''
import numpy as np
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
def print_type(numpY):
    print(numpY)
    print(numpY.ndim)
    print(numpY.shape)
    print(numpY.size)
    print(numpY.dtype)
    print(numpY.itemsize)
    print(len(numpY)) 
    print(type(numpY))

print("a:")
print_type(a)
print("b:")
print_type(b)
print("c:")
print_type(c)


'''

In [ ]:

a = np.random.randint(10, size=6) 

'''
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(len(a)) 
print(type(a))
'''

[1 1 2 0 1 6]
1
(6,)
6
int64
8
6
<class 'numpy.ndarray'>


In [ ]:
b = np.random.randint(10, size=(3,4)) 

'''
print(b)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(len(b)) 
print(type(b))
'''

[[0 7 9 3]
 [8 2 7 7]
 [9 3 3 3]]
2
(3, 4)
12
int64
8
3
<class 'numpy.ndarray'>


In [ ]:
c = np.random.randint(10, size=(2,3,2)) 

'''
print(c)
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(len(c)) 
print(type(c))
'''

[[[1 3]
  [2 8]
  [2 5]]

 [[0 0]
  [8 0]
  [1 6]]]
3
(2, 3, 2)
12
int64
8
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [ ]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[7, 6, 7, 3, 7, 5]
[7, 6, 7, 3, 7, 5]


In [ ]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[5, 7, 4, 6], [9, 4, 0, 1], [9, 1, 2, 9]]
[array([5, 7, 4, 6]), array([9, 4, 0, 1]), array([9, 1, 2, 9])]


In [ ]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]
[array([[0, 4],
       [0, 1],
       [9, 5]]), array([[8, 7],
       [8, 2],
       [6, 0]])]


In [ ]:
import numpy as np
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2))
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    return [tolist(obj) for obj in iterable]

print(tolist(a))
print(tolist(b))
print(tolist(c))

[7, 6, 7, 3, 7, 5]
[[5, 7, 4, 6], [9, 4, 0, 1], [9, 1, 2, 9]]
[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]
