# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [3]:
import numpy as np
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
print("np.zeros 創建的陣列中值都為0")
print("np.empty 創建的陣列中值不為0，但各元素值接近0，且np.empty不會初始化陣列內元素的初始值，所以內容將會是不確定的")
print("如需初始化則使用np.zeros((x,y))；若不須初始化使用np.empty((x,y))大量數據的狀況下處理時間較短")


'\nYour Code\n'

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [9]:
import numpy as np
a = np.random.rand(2, 3)
np.set_printoptions(precision=0)
print(a)

[[1. 1. 1.]
 [0. 1. 0.]]
[[1. 1. 1.]
 [0. 1. 0.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [11]:
import numpy as np
m = 20
n = 40
a = np.random.randint(m,n,(2,3))
print(a)


[[28 36 23]
 [31 35 25]]
