# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [5]:
import numpy as np
a = np.arange(9).reshape(3,3)
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
print("a.sum() , np.sum(a) 輸出結果相同，皆是回傳所有加總的值")
print("sum(a)是以預設從 axis = 0 的方向做加總，得到一個一維的矩陣")

36
36
[ 9 12 15]
a.sum() , np.sum(a) 輸出結果相同，皆是回傳所有加總的值
sum(a)是以預設從 axis = 0 的方向做加總，得到一個一維的矩陣


### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [8]:
#正規化(normalization)是將特徵資料按比例縮放，讓資料落在某一特定的區間
import numpy as np
A = np.random.random((5, 5))
print(A)
B =  (A - A.min()) / (A.max() - A.min())
print("正規化後:")
print(B)



[[0.26196948 0.57314294 0.02629028 0.76274246 0.33367056]
 [0.58150815 0.32453491 0.94560752 0.58737275 0.34219892]
 [0.85499631 0.36564876 0.1369541  0.81780524 0.13000166]
 [0.50651194 0.9577412  0.92609667 0.83192379 0.99715932]
 [0.32017523 0.53298638 0.59205852 0.62228767 0.97133898]]
正規化後:
[[0.24275076 0.56326099 0.         0.75854946 0.31660324]
 [0.57187721 0.30719347 0.9469014  0.57791777 0.32538749]
 [0.85357138 0.34954094 0.11398429 0.8152644  0.10682324]
 [0.49463073 0.95939914 0.92680512 0.82980657 1.        ]
 [0.30270297 0.52189953 0.58274414 0.61388032 0.97340492]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [13]:
import numpy as np
A = np.random.random(10)
A[A.argmax()] = -1
print(A)

[ 0.27805955 -1.          0.20620637  0.47456893  0.13355384  0.07118444
  0.40657842  0.00170069  0.54304164  0.49662848]
